import type { Metadata } from 'next';
import './styles/index.css';
import 'uno.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='overflow-x-hidden bg-white text-black antialiased transition-colors dark:bg-gray-900 dark:text-white'>{children}</body>
    </html>
  );
}
